string concetanation:
'''x='earth'
y='moon'
z=(x+y)
print(type(z))'''
'''x='earth'
y='moon'
z='sun'
v=print(x+y+z)
print(type(v))'''

string repetation:
'''a='blackhole'
print(a*5)'''

complex data type:
'''x=3+8j
print(x)
print(type(x))
y=7+5j
print(y)
print(type(y))
z=x+y
print(z)
print(type(z))'''
'''a=6+9j
print(a)
print(a.real)
print(a.imag)'''

boolean type:
x='true'
print(x)
print(type(x))
y='false'
print(y)
print(type(y))
z=x+y
print(z)
print(type(z))
